import { Dimensions } from "react-native";

const width = Dimensions.get("screen").width * 0.9 - 80;
const height = Dimensions.get("window").height * 0.7 - 80;

const formations = {
  4231: [
    { key: "0", name: "GK", number: "1", xPos: width * 0.5, yPos: height },
    {
      key: "1",
      name: "RB",
      number: "2",
      xPos: width * 0.95,
      yPos: height * 0.75,
    },
    {
      key: "2",
      name: "CB",
      number: "5",
      xPos: width * 0.7,
      yPos: height * 0.85,
    },
    {
      key: "3",
      name: "CB",
      number: "4",
      xPos: width * 0.3,
      yPos: height * 0.85,
    },
    {
      key: "4",
      name: "LB",
      number: "3",
      xPos: width * 0.05,
      yPos: height * 0.75,
    },
    {
      key: "5",
      name: "CDM",
      number: "8",
      xPos: width * 0.27,
      yPos: height * 0.6,
    },
    {
      key: "6",
      name: "CDM",
      number: "6",
      xPos: width * 0.73,
      yPos: height * 0.6,
    },
    {
      key: "7",
      name: "CAM",
      number: "10",
      xPos: width * 0.5,
      yPos: height * 0.35,
    },
    {
      key: "8",
      name: "LW",
      number: "7",
      xPos: width * 0.1,
      yPos: height * 0.35,
    },
    {
      key: "9",
      name: "RW",
      number: "11",
      xPos: width * 0.9,
      yPos: height * 0.35,
    },
    {
      key: "10",
      name: "ST",
      number: "9",
      xPos: width * 0.5,
      yPos: height * 0.15,
    },
  ],
  433: [
    { key: "0", name: "GK", number: "1", xPos: width * 0.5, yPos: height },
    {
      key: "1",
      name: "RB",
      number: "2",
      xPos: width * 0.95,
      yPos: height * 0.75,
    },
    {
      key: "2",
      name: "CB",
      number: "5",
      xPos: width * 0.7,
      yPos: height * 0.85,
    },
    {
      key: "3",
      name: "CB",
      number: "4",
      xPos: width * 0.3,
      yPos: height * 0.85,
    },
    {
      key: "4",
      name: "LB",
      number: "3",
      xPos: width * 0.05,
      yPos: height * 0.75,
    },
    {
      key: "5",
      name: "CM",
      number: "8",
      xPos: width * 0.2,
      yPos: height * 0.47,
    },
    {
      key: "6",
      name: "CDM",
      number: "6",
      xPos: width * 0.5,
      yPos: height * 0.6,
    },
    {
      key: "7",
      name: "CM",
      number: "10",
      xPos: width * 0.8,
      yPos: height * 0.47,
    },
    {
      key: "8",
      name: "LW",
      number: "7",
      xPos: width * 0.08,
      yPos: height * 0.2,
    },
    {
      key: "9",
      name: "RW",
      number: "11",
      xPos: width * 0.92,
      yPos: height * 0.2,
    },
    {
      key: "10",
      name: "ST",
      number: "9",
      xPos: width * 0.5,
      yPos: height * 0.15,
    },
  ],
  442: [
    { key: "0", name: "GK", number: "1", xPos: width * 0.5, yPos: height },
    {
      key: "1",
      name: "RB",
      number: "2",
      xPos: width * 0.95,
      yPos: height * 0.75,
    },
    {
      key: "2",
      name: "CB",
      number: "5",
      xPos: width * 0.7,
      yPos: height * 0.85,
    },
    {
      key: "3",
      name: "CB",
      number: "4",
      xPos: width * 0.3,
      yPos: height * 0.85,
    },
    {
      key: "4",
      name: "LB",
      number: "3",
      xPos: width * 0.05,
      yPos: height * 0.75,
    },
    {
      key: "5",
      name: "CDM",
      number: "8",
      xPos: width * 0.27,
      yPos: height * 0.55,
    },
    {
      key: "6",
      name: "CDM",
      number: "6",
      xPos: width * 0.73,
      yPos: height * 0.55,
    },
    {
      key: "7",
      name: "ST",
      number: "10",
      xPos: width * 0.28,
      yPos: height * 0.2,
    },
    {
      key: "8",
      name: "LW",
      number: "7",
      xPos: width * 0.05,
      yPos: height * 0.4,
    },
    {
      key: "9",
      name: "RW",
      number: "11",
      xPos: width * 0.95,
      yPos: height * 0.4,
    },
    {
      key: "10",
      name: "ST",
      number: "9",
      xPos: width * 0.72,
      yPos: height * 0.2,
    },
  ],
  352: [
    { key: "0", name: "GK", number: "1", xPos: width * 0.5, yPos: height },
    {
      key: "1",
      name: "RCB",
      number: "2",
      xPos: width * 0.85,
      yPos: height * 0.75,
    },
    {
      key: "2",
      name: "CB",
      number: "5",
      xPos: width * 0.5,
      yPos: height * 0.85,
    },
    {
      key: "3",
      name: "LCB",
      number: "4",
      xPos: width * 0.15,
      yPos: height * 0.75,
    },
    {
      key: "4",
      name: "LWB",
      number: "3",
      xPos: width * 0.05,
      yPos: height * 0.4,
    },
    {
      key: "5",
      name: "CDM",
      number: "8",
      xPos: width * 0.29,
      yPos: height * 0.57,
    },
    {
      key: "6",
      name: "CDM",
      number: "6",
      xPos: width * 0.71,
      yPos: height * 0.57,
    },
    {
      key: "7",
      name: "CAM",
      number: "10",
      xPos: width * 0.5,
      yPos: height * 0.35,
    },
    {
      key: "8",
      name: "ST",
      number: "7",
      xPos: width * 0.28,
      yPos: height * 0.15,
    },
    {
      key: "9",
      name: "RWB",
      number: "11",
      xPos: width * 0.95,
      yPos: height * 0.4,
    },
    {
      key: "10",
      name: "ST",
      number: "9",
      xPos: width * 0.72,
      yPos: height * 0.15,
    },
  ],
  343: [
    { key: "0", name: "GK", number: "1", xPos: width * 0.5, yPos: height },
    {
      key: "1",
      name: "RCB",
      number: "2",
      xPos: width * 0.9,
      yPos: height * 0.73,
    },
    {
      key: "2",
      name: "CB",
      number: "5",
      xPos: width * 0.5,
      yPos: height * 0.8,
    },
    {
      key: "3",
      name: "LCB",
      number: "4",
      xPos: width * 0.1,
      yPos: height * 0.73,
    },
    {
      key: "4",
      name: "LWB",
      number: "3",
      xPos: width * 0.05,
      yPos: height * 0.43,
    },
    {
      key: "5",
      name: "CDM",
      number: "8",
      xPos: width * 0.32,
      yPos: height * 0.55,
    },
    {
      key: "6",
      name: "CDM",
      number: "6",
      xPos: width * 0.68,
      yPos: height * 0.55,
    },
    {
      key: "7",
      name: "RWB",
      number: "10",
      xPos: width * 0.95,
      yPos: height * 0.43,
    },
    {
      key: "8",
      name: "LW",
      number: "7",
      xPos: width * 0.1,
      yPos: height * 0.2,
    },
    {
      key: "9",
      name: "RW",
      number: "11",
      xPos: width * 0.9,
      yPos: height * 0.2,
    },
    {
      key: "10",
      name: "ST",
      number: "9",
      xPos: width * 0.5,
      yPos: height * 0.15,
    },
  ],
};

export default formations;
